import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/unenv/runtime/polyfill/fetch.node.mjs';
export { l as localFetch } from './chunks/nitro-prerenderer.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/h3/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/ohmyfetch/dist/node.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/destr/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/radix3/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/unenv/runtime/fetch/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/hookable/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/scule/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/defu/dist/defu.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/ohash/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/unstorage/dist/index.mjs';
import 'file://C:/Users/Fraser/Websites/2022/nuxt3-example/node_modules/ufo/dist/index.mjs';
